# Generated by Django 4.1.3 on 2023-07-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_feedbackk_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackk',
            name='school',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
